### ISSUE TITLE
pr, issue 템플릿

### ISSUE THREAD

**Issue by devBuzz142** [prgrms-web-devcourse/Team-Books-CheckMoi-FE#34]
<img width="180" alt="image" src="https://user-images.githubusercontent.com/19660039/182527573-97f6ba58-945b-4c08-ac40-8b6b1f793278.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/19660039/182527648-4e0fb9df-7b0c-40ec-b0e4-dcf47ccbb6af.png">

pr, issue 템플릿 설정을 위한 문서 작성

**Comment by feel0321** [comment]
@devBuzz142 이거 닫아도 되나요?
